### ISSUE TITLE
怎么处理汽车之家网页源码中文字被替换的？

### ISSUE THREAD

**Issue by burette** [swoiow/autohome#1]
您好？这些数据都是您抓取的么？您是怎样抓取数据的？主要是怎么处理汽车之家网页源码中文字被替换的？这几天在研究这个，这个问题一直处理不了。感谢。

**Comment by swoiow** [comment]
车型数据来自 api 。font-family 的问题，我想主要思路是，截图 - 识别 - 映射。具体来说，你得到了页面源码，那 bs4.etree.get_text(strip=True) 得到只有文字部分，截图，把图给腾讯，谷歌，等等的 orc 接口。或者枚举 Unicode Character Ranges (http://jrgraphix.net/research/unicode.php)，得到一个 html 页面，放上font-family，截图，给接口 ocr。

**Comment by swoiow** [comment]
> 您好？这些数据都是您抓取的么？您是怎样抓取数据的？主要是怎么处理汽车之家网页源码中文字被替换的？这几天在研究这个，这个问题一直处理不了。感谢。

车型数据来自 api 。font-family 的问题，我想主要思路是，截图 - 识别 - 映射。具体来说，你得到了页面源码，那 bs4.etree.get_text(strip=True) 得到只有文字部分，截图，把图给腾讯，谷歌，等等的 orc 接口。或者枚举 Unicode Character Ranges ( http://jrgraphix.net/research/unicode.php )，得到一个 html 页面，放上font-family，截图，给接口 ocr。
