### ISSUE TITLE
请问是否方便共享代码？需要获取每个车型下的细分车型，目前数据中是数字代码，谢谢

### ISSUE THREAD

**Issue by hxf829** [swoiow/autohome#3]
![image](https://user-images.githubusercontent.com/211883/237025843-3a3192d9-1bbd-44f3-9eb8-556c4d9c57a6.png)

**Comment by swoiow** [comment]
1. 相关示例代码github上很多。
2. 其次，车型问题不存在的。

**Comment by swoiow** [comment]
1. 相关示例代码github上很多。
2. 其次，车型问题不存在的。
