### ISSUE TITLE
请问能否支持历史停售车型啊

### ISSUE THREAD

**Issue by Azuresonance** [swoiow/autohome#4]
或者希望能开放源码，我自己折腾折腾也行（
最近想买二手车
谢谢大佬

**Comment by swoiow** [comment]
1. 由项目建立到现在，是可以通过git来回溯历史车型的
2. 有些下架的进口车，年代久远的车，这个你给个示例地址吧。我印象看过是接口没返回。
3. 源码，网上随便捞就行了，组装的事儿，不复杂吧。我源码依赖二开框架的。
