### ISSUE TITLE
几个小问题反馈

### ISSUE THREAD

**Issue by leilintao** [swoiow/autohome#5]
1、车型名字丢失，如：汽车之家配置表中子车型名字「极氪007 2024款 后驱增强版 75kWh」，您这里显示的是一串数字
2、配置内容确实，如：汽车之家极氪007车型配置表中，「主座椅调节方式」中详细标注了主驾座椅调节方向和自由度，但是您的配置表中缺失相关信息
3、配置项排序顺序和汽车之家不一样

**Comment by swoiow** [comment]
https://github.com/swoiow/autohome/issues/3#issuecomment-1543680222
